# Generated by Django 3.0.2 on 2020-02-24 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome da imagem', models.CharField(max_length=200)),
                ('Caminho da imagem', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao do preco', models.CharField(max_length=200)),
                ('Valor do preco', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('Valor de desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome do produto', models.CharField(max_length=200)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Price')),
                ('url_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Image')),
            ],
        ),
    ]
