# Generated by Django 2.2.12 on 2020-04-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_site', models.CharField(max_length=50, verbose_name='Texto em destaque do banner')),
                ('icone', models.CharField(max_length=50, verbose_name='Texto em destaque do banner')),
            ],
        ),
    ]
