# Generated by Django 2.2.12 on 2020-04-24 22:14

from django.db import migrations, models
import faicon.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='ativo',
            field=models.BooleanField(default=False, verbose_name='Essa informacao esta ativa?'),
        ),
        migrations.AddField(
            model_name='site',
            name='icon',
            field=faicon.fields.FAIconField(blank=True, max_length=50, verbose_name='Icons prontos para uso'),
        ),
        migrations.AlterField(
            model_name='site',
            name='icone',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='Icone para metatag do site'),
        ),
        migrations.AlterField(
            model_name='site',
            name='nome_site',
            field=models.CharField(max_length=50, verbose_name='Nome do site caso nao tenha logo e para meta tag'),
        ),
    ]
