# Generated by Django 2.2.12 on 2020-04-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageproduct',
            name='image_url',
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='img',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
