# Generated by Django 2.2.12 on 2020-04-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200422_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL', verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='img',
            field=models.ImageField(upload_to='image', verbose_name='Caminho da imagem'),
        ),
    ]
