# Generated by Django 2.2.12 on 2020-04-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200422_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL', verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL', verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL', verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='sku',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL', verbose_name='Slug'),
        ),
    ]
