# Generated by Django 2.2.12 on 2020-04-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200422_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome da imagem'),
        ),
    ]
