# Generated by Django 2.2.12 on 2020-04-24 16:52

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200424_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='img',
            field=sorl.thumbnail.fields.ImageField(upload_to='image', verbose_name='Caminho da imagem'),
        ),
    ]
