# Generated by Django 2.2.12 on 2020-04-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200424_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='img',
            field=models.ImageField(upload_to='image', verbose_name='Caminho da imagem'),
        ),
    ]
