# Generated by Django 2.2.12 on 2020-04-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200424_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome para especificacao ex: Detalhes')),
                ('text', models.TextField(verbose_name='Texto da especificacao')),
            ],
        ),
    ]
