# Generated by Django 2.2.12 on 2020-04-29 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='sku',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Sku', verbose_name='sku a ser vinculado'),
            preserve_default=False,
        ),
    ]
